services:
  postgres:
    image: postgres:latest
    container_name: clube-de-vantagens_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1405
      POSTGRES_DB: clube-de-vantagens-api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
